<a href="https://colab.research.google.com/github/Chetan3520/TensorFlowDeveloper/blob/main/TensorFlowDEV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **TensorFlow Devloper Practice**

In [ ]:
import tensorflow as tf

# Creating the  tensor  with tf.constant()

*   Scaler is zero dimentional Tensor
*   vector is one dimentional Tensor


In [ ]:
T1=tf.constant(12)

In [ ]:
T1.ndim

0

In [ ]:
T2=tf.constant([1,2,4])

In [ ]:
T2.ndim

1

In [ ]:
T3=tf.constant([[1,2,4],
               [1,5,3]])

In [ ]:
T3.ndim



2

In [ ]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

# **Creating Tensors with tf.Variable()**
You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using tf.Variable().

The difference between tf.Variable() and tf.constant() is tensors created with tf.constant() are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with tf.Variable() are mutable (can be changed).

In [ ]:
t1=tf.Variable([[1,2,4,5],[3,5,3,3]])
t1

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 4, 5],
       [3, 5, 3, 3]], dtype=int32)>

In [ ]:
t1[1,1].assign(345)

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[  1,   2,   4,   5],
       [  3, 345,   3,   3]], dtype=int32)>

# Creating the Random Tensor

In [ ]:
# Create a random number generator

random_t=tf.random.Generator.from_seed(42)

random_t.normal((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
generator = tf.random.Generator.from_seed(42)  # You can use any seed value

# Generate a random tensor with uniform distribution
shape = (2, 3)
random_tensor = generator.uniform(shape, minval=0, maxval=1)

print(random_tensor)

tf.Tensor(
[[0.7493447  0.73561966 0.45230794]
 [0.49039817 0.1889317  0.52027524]], shape=(2, 3), dtype=float32)


In [ ]:
#Exponential is not present in the Generator.

# Create a random number generator
generator = tf.random.Generator.from_seed(42)  # You can use any seed value

# Generate a random tensor with exponential distribution
shape = (2, 3)
random_tensor = generator.exponential(shape, 1.0)  # The second parameter is the scale parameter

print(random_tensor)

AttributeError: 'Generator' object has no attribute 'exponential'

# Shuffle the order of the elements in tensor


*   To create the Randomness in the data we need to shuffle it sometimes to satisfy asssumption of the indepenedence of the data points

tf.radom.shuffle(tensor_to_shuffle)


In [ ]:
not_shuffled=tf.constant([[10,3],[6,4],[9,4]]);not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  3],
       [ 6,  4],
       [ 9,  4]], dtype=int32)>

In [ ]:
not_shuffled.ndim

2

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  4],
       [10,  3],
       [ 9,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed=40) #order not fixed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  3],
       [ 6,  4],
       [ 9,  4]], dtype=int32)>

In [ ]:
#to fix the Random Order
tf.random.set_seed(40)
tf.random.shuffle(not_shuffled,seed=40)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9,  4],
       [10,  3],
       [ 6,  4]], dtype=int32)>

In [ ]:
T2=tf.constant([[1,24,4],[1,23,44]]);T2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1, 24,  4],
       [ 1, 23, 44]], dtype=int32)>

In [ ]:
tf.random.shuffle(T2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1, 23, 44],
       [ 1, 24,  4]], dtype=int32)>

# Other way to make Tensors
numpy

In [ ]:
#tensor of ones
tf.ones(10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
#tensor of zeros
tf.zeros(10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

# **Tensor from Nunpy Array**

*   tensorflow tensors can be run on GPU much faster for numerical computting



In [ ]:
import numpy as np
numpy_A=np.arange(1,101,1,'int')

In [ ]:
T=tf.constant(numpy_A);T

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])>

In [ ]:
T2=tf.constant(numpy_A,shape=(2,5,10));T2

<tf.Tensor: shape=(2, 5, 10), dtype=int64, numpy=
array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])>

# Getting Information from Tensors

*   shape
*   rank
*  Axis or dimention
*   size




In [ ]:
T2.shape  #shape

TensorShape([2, 5, 10])

In [ ]:
T2.ndim #rank

3

In [ ]:
tf.size(T2)

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [ ]:
T3=tf.zeros(shape=[2,3,4,4]);T3

<tf.Tensor: shape=(2, 3, 4, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
T3.shape,T3.ndim,tf.size(T3)

(TensorShape([2, 3, 4, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=96>)

In [ ]:
2*3*4*4

96

In [ ]:
print("Datatype of the every element:",T3.dtype)
print("-----------------------------------------------------")
print("Number of the dimention(rank):",T3.ndim)
print("-----------------------------------------------------")
print("Shape of the Tensor:",T3.shape)
print("-----------------------------------------------------")
print("Elements along the 0 axis:",T3.shape[0])
print("-----------------------------------------------------")
print("Elements along the last axis:",T3[-1])
print("-----------------------------------------------------")
print("Total numner of elments in our tensor:",tf.size(T3))

Datatype of the every element: <dtype: 'float32'>
-----------------------------------------------------
Number of the dimention(rank): 4
-----------------------------------------------------
Shape of the Tensor: (2, 3, 4, 4)
-----------------------------------------------------
Elements along the 0 axis: 2
-----------------------------------------------------
Elements along the last axis: tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(3, 4, 4), dtype=float32)
-----------------------------------------------------
Total numner of elments in our tensor: tf.Tensor(96, shape=(), dtype=int32)


# Indexing the Tensors

In [ ]:
T3

<tf.Tensor: shape=(2, 3, 4, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Getting first two elments of the each dimentions
T3[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get first element from  each dimention from each index except for the final one


In [ ]:
T3.shape

TensorShape([2, 3, 4, 4])

In [ ]:
T3[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#exept second last
T3[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#rank two tensor
rank_2_tens=tf.constant([[1,2,3,4],[3,4,5,6]])

In [ ]:
rank_2_tens.ndim

2

In [ ]:
rank_2_tens.shape


TensorShape([2, 4])

In [ ]:
rank_2_tens

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [3, 4, 5, 6]], dtype=int32)>

In [ ]:
#get the last element of the each of the row  of rank_2_tens
rank_2_tens[:,-1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

Addding Extra Dimention two rank 2 tensor
(Expand Dimention)

In [ ]:
rank_3_tensor=rank_2_tens[...,tf.newaxis];rank_3_tensor # '...' indicates previous all axis here axis 1 and 2

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[3],
        [4],
        [5],
        [6]]], dtype=int32)>

# OR

In [ ]:
tf.expand_dims(rank_2_tens,axis=-1) #-1 means expand the last axis

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[3],
        [4],
        [5],
        [6]]], dtype=int32)>

# [Manipulation Tensors]/ Tensor Operations

**Basic Operations**



In [ ]:
tensor=tf.constant(np.arange(4),shape=(2,2));tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 1],
       [2, 3]])>

In [ ]:
#Adding values to the tensors
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[10, 11],
       [12, 13]])>

In [ ]:
tensor*2  #mult

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 2],
       [4, 6]])>

In [ ]:
tensor/2 #devide

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0. , 0.5],
       [1. , 1.5]])>

In [ ]:
tensor-1 #sub


<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[-1,  0],
       [ 1,  2]])>

In [ ]:
tf.multiply(tensor,tensor-1)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 0],
       [2, 6]])>

# Matrix Multiplication
*   Condition : No of row of one matrix = no of columns of the other matrix (Vice-Versa)


Using


1.   Element to Element multiplication
*   '*'  :  python operator
*   multiply  : tensorflow
2.   Algebric Multiplication
*   tensordot: matmul
*   tensordot: tensorflow














In [ ]:
tensor,tensor+1

(<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[0, 1],
        [2, 3]])>,
 <tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4]])>)

In [ ]:
tensor*tensor+1 #Element wise

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 1,  2],
       [ 5, 10]])>

In [ ]:
tf.linalg.matmul(tensor,tensor+1
                 ) #Actual algebric multiplication of the matrix

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 3,  4],
       [11, 16]])>

In [ ]:
tensor@(tensor+1)   # Multiplication using '@' python operator

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 3,  4],
       [11, 16]])>

In [ ]:
tf.matmul(tensor,tensor+1)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 3,  4],
       [11, 16]])>

In [ ]:
tf.constant(np.random.rand(30),shape=(2,3,5))

<tf.Tensor: shape=(2, 3, 5), dtype=float64, numpy=
array([[[0.25883489, 0.95709992, 0.51217165, 0.92689581, 0.39575534],
        [0.49479195, 0.53048461, 0.15018112, 0.20100691, 0.9490452 ],
        [0.93445557, 0.92652643, 0.26785989, 0.7236016 , 0.15174042]],

       [[0.50712837, 0.66445721, 0.57261744, 0.52762254, 0.96474889],
        [0.29345107, 0.18410023, 0.87048621, 0.44495778, 0.23750566],
        [0.12137604, 0.71006343, 0.47742607, 0.48993989, 0.6376116 ]]])>

In [ ]:
T23=tf.constant([[1,2,3],[5,2,1]]);T23

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 2, 1]], dtype=int32)>

**Using Reshape and transpose we can do matrix multiplication**


*   reshape: resuffling
*   transpose: revert the axis


> Indented block



In [ ]:
T23@(tf.reshape(T23,shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 15],
       [13, 21]], dtype=int32)>

In [ ]:
tf.reshape(T23,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5],
       [2, 1]], dtype=int32)>

In [ ]:
#we also multiply matrix with it transpose
T23 @ tf.transpose(T23)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 12],
       [12, 30]], dtype=int32)>

In [ ]:
tf.matmul(T23,tf.transpose(T23))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 12],
       [12, 30]], dtype=int32)>

In [ ]:
tf.tensordot(T23,tf.transpose(T23),axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 12],
       [12, 30]], dtype=int32)>

# Changing Data Types of the Tensor
tf.cast()

In [ ]:
c=tf.constant([1.7,7.4])

In [ ]:
c.dtype

tf.float32

In [ ]:
c=tf.cast(c,dtype=tf.int32)  #float to integer
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

In [ ]:
c.dtype

tf.int32

# Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:


*   tf.reduce_min() - find the minimum value in a tensor.
*   tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
*   tf.reduce_mean() - find the mean of all elements in a tensor.
*   tf.reduce_sum() - find the sum of all elements in a tensor.







*   Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [ ]:
tensor2=tf.constant(np.random.randint(1,1000,50),shape=(2,5,5))
tensor2

<tf.Tensor: shape=(2, 5, 5), dtype=int64, numpy=
array([[[  7, 766, 160, 611,  37],
        [907, 521, 340,  70, 619],
        [565, 719, 932, 138, 404],
        [816, 256, 199, 260, 763],
        [864, 221, 728, 892, 902]],

       [[995, 414, 116, 961, 156],
        [976, 399, 358, 669, 448],
        [299, 153,  76, 408, 911],
        [158, 486, 109,  52, 544],
        [880, 840, 937,  71, 619]]])>

In [ ]:
#find minimum
tf.reduce_min(tensor2)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
#find maximum
tf.reduce_max(tensor2)

<tf.Tensor: shape=(), dtype=int64, numpy=995>

In [ ]:
#find the mean
tf.reduce_mean(tensor2)

<tf.Tensor: shape=(), dtype=int64, numpy=494>

In [ ]:
#find the sum
tf.reduce_sum(tensor2)

<tf.Tensor: shape=(), dtype=int64, numpy=24732>

# inding the positional maximum and minimum
**How about finding the position a tensor where the maximum value occurs?**

This is helpful when you want to line up your labels (say ['Green', 'Blue', 'Red']) with your prediction probabilities tensor (e.g. [0.98, 0.01, 0.01]).


In this case, the predicted label (the one with the highest prediction probability) would be 'Green'.

You can do the same for the minimum (if required) with the following:


*   tf.argmax() - find the position of the maximum element in a given tensor.
*   tf.argmin() - find the position of the minimum element in a given tensor.



In [ ]:
tensor3=tf.constant(np.random.rand(50))
tensor3

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.2864895 , 0.11511826, 0.38117876, 0.51433159, 0.70190674,
       0.17674496, 0.1794116 , 0.55475927, 0.79997975, 0.10981206,
       0.05893322, 0.42030853, 0.46364089, 0.39655759, 0.84741499,
       0.07743043, 0.02320127, 0.97435961, 0.88274277, 0.63670451,
       0.95144208, 0.11671332, 0.89924412, 0.62617022, 0.13797457,
       0.83793721, 0.02348565, 0.65752303, 0.31064961, 0.04230873,
       0.62618716, 0.69646436, 0.39517   , 0.35496944, 0.0776583 ,
       0.84431254, 0.11208437, 0.43208482, 0.71257204, 0.07414575,
       0.27155482, 0.40959011, 0.73303682, 0.81114362, 0.23436186,
       0.14525713, 0.67601036, 0.83036873, 0.05640715, 0.11983322])>

In [ ]:
#find the maximum number position in the tensor3
tf.argmax(tensor3)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
tf.argmin(tensor3)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

## Squeezing the Tensor (Removing all the single dimentions)
If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().



In [ ]:
tensor_squeez=tf.constant(np.random.randint(1,10,20),shape=(1,1,1,1,20))
tensor_squeez

<tf.Tensor: shape=(1, 1, 1, 1, 20), dtype=int64, numpy=array([[[[[9, 2, 6, 7, 6, 6, 8, 4, 4, 2, 7, 5, 3, 2, 2, 9, 1, 9, 5, 2]]]]])>

In [ ]:

tf.squeeze(tensor_squeez)

<tf.Tensor: shape=(20,), dtype=int64, numpy=array([4, 9, 9, 9, 4, 6, 8, 5, 7, 3, 1, 2, 2, 7, 3, 3, 3, 5, 9, 5])>

## **One Hot Encoding**
If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [ ]:
friends=[1,2,3,4]
#one hot encode them
tf.one_hot(friends,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Specify custom values for on and off encoding
tf.one_hot(friends, depth=4, on_value="kinu", off_value="pinu")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'pinu', b'kinu', b'pinu', b'pinu'],
       [b'pinu', b'pinu', b'kinu', b'pinu'],
       [b'pinu', b'pinu', b'pinu', b'kinu'],
       [b'pinu', b'pinu', b'pinu', b'pinu']], dtype=object)>

## **Squaring, log, square root**
Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:


* **tf.square()** - get the square of every value in a tensor.
* **tf.sqrt()** - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
* **tf.math.log()** - get the natural log of every value in a tensor (elements need to floats)



In [ ]:
H=tf.constant(np.arange(1,10))


In [ ]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
#Square root of it
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [ ]:
H=tf.cast(H,dtype='float')
#Square root of it
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#finding the log
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# **Manipulating tf.varible()**

Tensors created with tf.Variable() can be changed in place using methods such as:


*   .assign() - assign a different value to a particular index of a variable tensor.
*  .add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.




In [ ]:
T_=tf.Variable(np.arange(1,6,1));
T_


<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [ ]:
T_[0].assign(50)

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([50,  2,  3,  4,  5])>

In [ ]:
T_.assign([0,0,0,0,0])
T_

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 0, 0, 0, 0])>

In [ ]:
T_.assign_add([1,10,10,100,1000]) #it assign as well as add

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([   1,   10,   10,  100, 1000])>

# Tensors and Numpy
We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:




*   np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).
*   tensor.numpy() - call on a tensor to
convert to an ndarray.


Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

In [ ]:
Array=np.array(T_)   #convert tensor to array
print('Type of Array',type(Array))

Type of Array <class 'numpy.ndarray'>


# Using @tf.function
In your TensorFlow adventures, you might come across Python functions which have the decorator  @tf.function.

If you aren't sure what Python decorators do, read RealPython's guide on them.

But in short, decorators modify a function in one way or another.

In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

For more on this, read the Better performnace with tf.function guide.

In [ ]:


def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))

function(x, y)


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>